#+TITLE: elf_commander_python
#+AUTHOR: Peter Polidoro
#+EMAIL: peter@polidoro.io

* Package Information
  - Name :: elf_commander_python
  - Version :: 2.0.0
  - License :: BSD
  - URL :: https://github.com/janelia-python/elf_commander_python
  - Author :: Peter Polidoro
  - Email :: peter@polidoro.io

  This Python package (elfcommander) creates a class named ElfCommander
  to communcate with and control the Janelia Elf. The Elf uses two
  hardware control devices, the mixed_signal_controller
  modular_device, and the bioshake_device. The
  mixed_signal_controller both switches the valves and reads the
  analog signals from the cylinder hall effect sensors. The
  bioshake_device controls the heater/shaker.

* Example Usage

  [[./example_config.yaml]]

  Open a terminal and enter:

  #+BEGIN_SRC sh
    source ~/virtualenvs/elfcommander/bin/activate
    elfcommander example_calibration.yaml example_config.yaml
  #+END_SRC

* Installation

  [[https://github.com/janelia-python/python_setup]]

*** Debian-based Linux Install Dependencies

    Open a terminal and enter:

    #+BEGIN_SRC sh
      sudo apt-get install git python-pip python-virtualenv python-dev build-essential -y
    #+END_SRC

** Linux and Mac OS X

   Open a terminal and enter:

   #+BEGIN_SRC sh
     mkdir ~/git
     cd ~/git
     git clone https://github.com/janelia-idf/elf_config.git
     git clone https://github.com/janelia-idf/elf.git
     cd elf
     git submodule init
     git submodule update
     cd ~
     mkdir ~/virtualenvs
     cd ~/virtualenvs
     virtualenv elfcommander
     source ~/virtualenvs/elfcommander/bin/activate
     pip install elfcommander
   #+END_SRC

   On linux, you may need to add yourself to the group 'dialout' in order
   to have write permissions on the USB port:

   Open a terminal and enter:

   #+BEGIN_SRC sh
     sudo usermod -aG dialout $USER
     sudo reboot
   #+END_SRC

** Windows

   Open a terminal and enter:

   #+BEGIN_SRC sh
     virtualenv C:\virtualenvs\elfcommander
     C:\virtualenvs\elfcommander\Scripts\activate
     pip install ipython
     pip install elfcommander
   #+END_SRC
